/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.ItemServico;
import model.dao.ItemServicoDAO;

/**
 *
 * @author Igor Túllio
 */
public class ViewItemServico extends javax.swing.JFrame {

    /**
     * Creates new form Comanda
     */
    public ViewItemServico() {
        super("ZOO - Cadastro de Itens e Serviços");
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtItemServico.getModel();
        jtItemServico.setRowSorter(new TableRowSorter(modelo));
        
        leTabela();
    }
    
    public void leTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jtItemServico.getModel();
        modelo.setNumRows(0);
        ItemServicoDAO itemDAO = new ItemServicoDAO();
        
        for (ItemServico p: itemDAO.ler()) {
            modelo.addRow(new Object[]{
               p.getCodigo(),
               p.getDescricao(),
               p.getValor()
            });                        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtItemServico = new javax.swing.JTable();
        tfDescricao = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        lbDescricao = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtItemServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtItemServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtItemServicoMouseClicked(evt);
            }
        });
        jtItemServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtItemServicoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtItemServico);

        lbDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDescricao.setText("Descrição");

        lbValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbValor.setText("Valor");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setText("Cadastro de Itens e Serviços");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDescricao))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbValor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btSalvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btExcluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btAlterar))))
                            .addComponent(lbTitulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExcluir)
                            .addComponent(btAlterar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        ItemServico item = new ItemServico();
        ItemServicoDAO itemDAO = new ItemServicoDAO();
        
        item.setDescricao(tfDescricao.getText());
        item.setValor(Double.parseDouble(tfValor.getText()));
        
        itemDAO.salvar(item);
        
        tfDescricao.setText("");
        tfValor.setText("");
        
        leTabela();        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jtItemServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtItemServicoKeyReleased
        // TODO add your handling code here:
        
        if (jtItemServico.getSelectedRow() != -1) {
            tfDescricao.setText(jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 1).toString());
            tfValor.setText(jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 2).toString());
        }
        
    }//GEN-LAST:event_jtItemServicoKeyReleased

    private void jtItemServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtItemServicoMouseClicked
        // TODO add your handling code here:
        
        if (jtItemServico.getSelectedRow() != -1) {
            tfDescricao.setText(jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 1).toString());
            tfValor.setText(jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 2).toString());
        }
        
    }//GEN-LAST:event_jtItemServicoMouseClicked

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        
        if (jtItemServico.getSelectedRow() != -1) {
            ItemServico item = new ItemServico();
            ItemServicoDAO itemDAO = new ItemServicoDAO();

            item.setDescricao(tfDescricao.getText());
            item.setValor(Double.parseDouble(tfValor.getText()));
            item.setCodigo((int)jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 0));
            itemDAO.alterar(item);

            tfDescricao.setText("");
            tfValor.setText("");

            leTabela();        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
        
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        
        if (jtItemServico.getSelectedRow() != -1) {
            ItemServico item = new ItemServico();
            ItemServicoDAO itemDAO = new ItemServicoDAO();

            item.setCodigo((int)jtItemServico.getValueAt(jtItemServico.getSelectedRow(), 0));
            itemDAO.excluir(item);

            tfDescricao.setText("");
            tfValor.setText("");

            leTabela();        
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtItemServico;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
