package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.FichaMedica;
import model.dao.FichaMedicaDAO;
import model.bean.FichaMedica;

/**
 * Tela do sistema de ficha médica do animal
 * 
 * @author Pedro Paul
 */
public class ViewFichaMedica extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ViewFichaMedica() {
        initComponents();
        setLocationRelativeTo(null); // Deixa o Frame Centralizado
        setResizable(false); // Não deixa mudar o tamanho da tela

        DefaultTableModel modeloFichaMedica = (DefaultTableModel) jtFichaMedica.getModel();
        jtFichaMedica.setRowSorter(new TableRowSorter(modeloFichaMedica));
        
        lerTabelaFichaMedica();
        
    }
    
    public void lerTabelaFichaMedica(){
        DefaultTableModel modelFichaMedica = (DefaultTableModel)jtFichaMedica.getModel();
        modelFichaMedica.setRowCount(0);
        FichaMedicaDAO fichaDAO = new FichaMedicaDAO();
        for (FichaMedica f : fichaDAO.ler()) {
            modelFichaMedica.addRow(new Object[]{
                f.getCodigo_FichaMedica(),
                f.getCodigo_Animal(),
                f.getDataNascimento_FichaMedica(),
                f.getDataEntradaZoo_FichaMedica(),
                f.getEstadoSaude_FichaMedica(),
                f.getPeso_FichaMedica(),
                f.getAltura_FichaMedica()
            });
        }//fim for
    }//fim metodo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpSistemaFichaMedica = new javax.swing.JTabbedPane();
        jpFichaMedica = new javax.swing.JPanel();
        spFichaMedica = new javax.swing.JScrollPane();
        jtFichaMedica = new javax.swing.JTable();
        jlCodAnimal = new javax.swing.JLabel();
        tfCodAnimal = new javax.swing.JTextField();
        jlNascimento = new javax.swing.JLabel();
        tfNascimento = new javax.swing.JTextField();
        jlEntrada = new javax.swing.JLabel();
        tfEntrada = new javax.swing.JTextField();
        jlEstadoSaude = new javax.swing.JLabel();
        tfEstadoSaude = new javax.swing.JTextField();
        jlPeso = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        jlAltura = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        jbInserir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        Pesquisar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jpAnimais = new javax.swing.JPanel();
        jpFuncionarios = new javax.swing.JPanel();
        jpProcedimentos = new javax.swing.JPanel();
        jpFornecedores = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Ficha Médica");
        setPreferredSize(new java.awt.Dimension(1024, 500));

        jtFichaMedica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód Ficha", "Cód Animal", "Nascimento", "Entrada", "Estado Saúde", "Peso", "Altura"
            }
        ));
        spFichaMedica.setViewportView(jtFichaMedica);

        jlCodAnimal.setText("Código do Animal");

        jlNascimento.setText("Data de Nascimento");

        jlEntrada.setText("Data de Entrada");

        jlEstadoSaude.setText("Estado de Saúde");

        jlPeso.setText("Peso");

        jlAltura.setText("Altura");

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar");

        Pesquisar.setText("Pesquisar");

        jbExcluir.setText("Excluir");

        javax.swing.GroupLayout jpFichaMedicaLayout = new javax.swing.GroupLayout(jpFichaMedica);
        jpFichaMedica.setLayout(jpFichaMedicaLayout);
        jpFichaMedicaLayout.setHorizontalGroup(
            jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spFichaMedica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                        .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAltura)
                                    .addComponent(jlPeso)
                                    .addComponent(jlEstadoSaude)
                                    .addComponent(jlEntrada))
                                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfEstadoSaude, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfPeso)
                                            .addComponent(tfAltura, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFichaMedicaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNascimento)
                                    .addComponent(jlCodAnimal))
                                .addGap(18, 18, 18)
                                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfCodAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(tfNascimento))))
                        .addGap(83, 83, 83)
                        .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbInserir)
                            .addComponent(jbAtualizar)
                            .addComponent(Pesquisar)
                            .addComponent(jbExcluir))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpFichaMedicaLayout.setVerticalGroup(
            jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFichaMedicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spFichaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodAnimal)
                    .addComponent(tfCodAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNascimento)
                    .addComponent(tfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEntrada)
                    .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoSaude)
                    .addComponent(tfEstadoSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPeso)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFichaMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAltura)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tpSistemaFichaMedica.addTab("Ficha Médica", jpFichaMedica);

        javax.swing.GroupLayout jpAnimaisLayout = new javax.swing.GroupLayout(jpAnimais);
        jpAnimais.setLayout(jpAnimaisLayout);
        jpAnimaisLayout.setHorizontalGroup(
            jpAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jpAnimaisLayout.setVerticalGroup(
            jpAnimaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        tpSistemaFichaMedica.addTab("Cadastro de Animais", jpAnimais);

        javax.swing.GroupLayout jpFuncionariosLayout = new javax.swing.GroupLayout(jpFuncionarios);
        jpFuncionarios.setLayout(jpFuncionariosLayout);
        jpFuncionariosLayout.setHorizontalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jpFuncionariosLayout.setVerticalGroup(
            jpFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        tpSistemaFichaMedica.addTab("Cadastro de Funcionários", jpFuncionarios);

        javax.swing.GroupLayout jpProcedimentosLayout = new javax.swing.GroupLayout(jpProcedimentos);
        jpProcedimentos.setLayout(jpProcedimentosLayout);
        jpProcedimentosLayout.setHorizontalGroup(
            jpProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jpProcedimentosLayout.setVerticalGroup(
            jpProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        tpSistemaFichaMedica.addTab("Procedimentos", jpProcedimentos);

        javax.swing.GroupLayout jpFornecedoresLayout = new javax.swing.GroupLayout(jpFornecedores);
        jpFornecedores.setLayout(jpFornecedoresLayout);
        jpFornecedoresLayout.setHorizontalGroup(
            jpFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jpFornecedoresLayout.setVerticalGroup(
            jpFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        tpSistemaFichaMedica.addTab("Fornecedores", jpFornecedores);

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpSistemaFichaMedica)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpSistemaFichaMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        setVisible(false); // Deixa o frame invisível
    }//GEN-LAST:event_btVoltarActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        try {
            //criar o objeto da classe FichaMedica
            FichaMedica ficha = new FichaMedica(
                    Integer.parseInt(tfCodAnimal.getText()),
                    tfNascimento.getText(),
                    tfEntrada.getText(),
                    tfEstadoSaude.getText(),
                    Float.parseFloat(tfPeso.getText()),
                    Float.parseFloat(tfAltura.getText())
            );
            //Pegar os textos e mandar pro banco
            FichaMedicaDAO.inserir(ficha);
            //Limpeza dos Campos
            tfCodAnimal.setText("");
            tfNascimento.setText("");
            tfEntrada.setText("");
            tfEstadoSaude.setText("");
            tfPeso.setText("");
            tfAltura.setText("");
            //atualiza a tabela FichaMedica
            lerTabelaFichaMedica();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
        }//fim try catch
    }//GEN-LAST:event_jbInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFichaMedica().setVisible(true); // Deixa o Frame visível
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlCodAnimal;
    private javax.swing.JLabel jlEntrada;
    private javax.swing.JLabel jlEstadoSaude;
    private javax.swing.JLabel jlNascimento;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JPanel jpAnimais;
    private javax.swing.JPanel jpFichaMedica;
    private javax.swing.JPanel jpFornecedores;
    private javax.swing.JPanel jpFuncionarios;
    private javax.swing.JPanel jpProcedimentos;
    private javax.swing.JTable jtFichaMedica;
    private javax.swing.JScrollPane spFichaMedica;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfCodAnimal;
    private javax.swing.JTextField tfEntrada;
    private javax.swing.JTextField tfEstadoSaude;
    private javax.swing.JTextField tfNascimento;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTabbedPane tpSistemaFichaMedica;
    // End of variables declaration//GEN-END:variables
}
