/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Comanda;
import model.bean.Visitante;
import model.dao.ComandaDAO;
import model.dao.VisitanteDAO;

/**
 *
 * @author igorgoncalves
 */
public class ViewComanda extends javax.swing.JFrame {

    /**
     * Creates new form ViewComanda
     */
    public ViewComanda() {
        super("ZOO - Abertura de Comanda");
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtComanda.getModel();
        jtComanda.setRowSorter(new TableRowSorter(modelo));
        
        leTabela();
    }
    
    public void leTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jtComanda.getModel();
        modelo.setNumRows(0);
        ComandaDAO comandaDAO = new ComandaDAO();
        
        for (Visitante v: comandaDAO.ler()) {
            modelo.addRow(new Object[]{
               v.getCpf(),
               v.getNome(),
               v.getTelefone()
            });                        
        }
        
    }
    
    public void leTabelaPorNome(String nomeVisitante){
        DefaultTableModel modelo = (DefaultTableModel) jtComanda.getModel();
        modelo.setNumRows(0);
        ComandaDAO comandaDAO = new ComandaDAO();
        
        for (Visitante v: comandaDAO.lerPorNome(nomeVisitante)) {
            modelo.addRow(new Object[]{
               v.getCpf(),
               v.getNome(),
               v.getTelefone()
            });                        
        }
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btPesquisarCPF = new javax.swing.JButton();
        tfBuscaCpf = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfBuscaNome = new javax.swing.JTextField();
        btPesquisarNome = new javax.swing.JButton();
        btAbrirComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComanda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setText("Comanda");

        btPesquisarCPF.setText("Pesquisar");
        btPesquisarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCPFActionPerformed(evt);
            }
        });

        lbCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCpf.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        tfBuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscaNomeActionPerformed(evt);
            }
        });

        btPesquisarNome.setText("Pesquisar");
        btPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarNomeActionPerformed(evt);
            }
        });

        btAbrirComanda.setText("Abrir Comanda");
        btAbrirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirComandaActionPerformed(evt);
            }
        });

        jtComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone"
            }
        ));
        jtComanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtComandaMouseClicked(evt);
            }
        });
        jtComanda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtComandaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtComanda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lbCpf))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBuscaNome)
                                    .addComponent(tfBuscaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btPesquisarCPF)
                                    .addComponent(btPesquisarNome))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCpf)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btPesquisarNome)
                            .addComponent(tfBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBuscaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPesquisarCPF)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscaNomeActionPerformed

    private void btPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarNomeActionPerformed
        // TODO add your handling code here:

        leTabelaPorNome(tfBuscaNome.getText());
        tfBuscaCpf.setText("");
        
    }//GEN-LAST:event_btPesquisarNomeActionPerformed

    private void btPesquisarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCPFActionPerformed
        // TODO add your handling code here:

        ComandaDAO comandaDAO = new ComandaDAO();
        
        String retorno = comandaDAO.verificaCPF(Double.parseDouble(tfBuscaCpf.getText()));
        if (retorno != null) {
            JOptionPane.showMessageDialog(null, "Visitante existente!");
            tfBuscaNome.setText(retorno);
        } else {
            JOptionPane.showMessageDialog(null, "Visitante não encontrado!");
        }
        
    }//GEN-LAST:event_btPesquisarCPFActionPerformed

    private void jtComandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtComandaMouseClicked
        // TODO add your handling code here:
        
        if (jtComanda.getSelectedRow() != -1) {
            tfBuscaCpf.setText(jtComanda.getValueAt(jtComanda.getSelectedRow(), 0).toString());
            tfBuscaNome.setText(jtComanda.getValueAt(jtComanda.getSelectedRow(), 1).toString());
        }
        
    }//GEN-LAST:event_jtComandaMouseClicked

    private void jtComandaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtComandaKeyReleased
        // TODO add your handling code here:
        
        if (jtComanda.getSelectedRow() != -1) {
            tfBuscaCpf.setText(jtComanda.getValueAt(jtComanda.getSelectedRow(), 0).toString());
            tfBuscaNome.setText(jtComanda.getValueAt(jtComanda.getSelectedRow(), 1).toString());
        }
        
    }//GEN-LAST:event_jtComandaKeyReleased

    private void btAbrirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirComandaActionPerformed
        // TODO add your handling code here:
        
        if (!tfBuscaCpf.getText().equals("")) {                    
            Comanda comanda = new Comanda();
            ComandaDAO comandaDAO = new ComandaDAO();

            comanda.setCpf_visitante(Double.parseDouble(tfBuscaCpf.getText()));

            comandaDAO.abre(comanda);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um CPF.");
        }
        
    }//GEN-LAST:event_btAbrirComandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirComanda;
    private javax.swing.JButton btPesquisarCPF;
    private javax.swing.JButton btPesquisarNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtComanda;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfBuscaCpf;
    private javax.swing.JTextField tfBuscaNome;
    // End of variables declaration//GEN-END:variables
}
